logging:
  path: /tmp/memory_log
  level: info #| debug | error

long_term_memory:
  derivative_deriver: sentence
  metadata_prefix: "[$timestamp] $producer_id: "
  embedder: my_embedder_id
  reranker: my_reranker_id
  vector_graph_store: my_storage_id

SessionDB:
  uri: sqlitetest.db

model:
  qianwen:
    model_vendor: qianwen
    model_name: "qwen-turbo"
    api_key: sk-1a9bd456f8ae476da2a2bd975737ce95
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    
storage:
  my_storage_id:
    vendor_name: neo4j
    host: neo4j
    port: 7687
    user: neo4j
    password: neo4j_password

profile_memory:
  model_name: qianwen

sessionMemory:
  model_name: qianwen
  message_capacity: 500
  max_message_length: 16000
  max_token_num: 8000

embedder:
  my_embedder_id:
    model_vendor: qianwen
    model_name: "text-embedding-v1"
    api_key: sk-1a9bd456f8ae476da2a2bd975737ce95
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

reranker:
  my_reranker_id:
    type: "rrf-hybrid"
    reranker_ids:
      - id_ranker_id
      - bm_ranker_id
      # - ce_ranker_id
  id_ranker_id:
    type: "identity"
  bm_ranker_id:
    type: "bm25"
  # ce_ranker_id:
  #   type: "cross-encoder"
  #   model_name: "cross-encoder/qnli-electra-base"














